import type { Metadata } from 'next';
import '../globals.css';
import Half from './_components/half';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="flex items-center  flex-1">
        <Half />
        <div className="flex-1">{children}</div>
      </div>
    </div>
  );
}
